// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Clients struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Descriptions         string   `protobuf:"bytes,5,opt,name=Descriptions,proto3" json:"Descriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clients) Reset()         { *m = Clients{} }
func (m *Clients) String() string { return proto.CompactTextString(m) }
func (*Clients) ProtoMessage()    {}
func (*Clients) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *Clients) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clients.Unmarshal(m, b)
}
func (m *Clients) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clients.Marshal(b, m, deterministic)
}
func (m *Clients) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clients.Merge(m, src)
}
func (m *Clients) XXX_Size() int {
	return xxx_messageInfo_Clients.Size(m)
}
func (m *Clients) XXX_DiscardUnknown() {
	xxx_messageInfo_Clients.DiscardUnknown(m)
}

var xxx_messageInfo_Clients proto.InternalMessageInfo

func (m *Clients) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Clients) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Clients) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Clients) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Clients) GetDescriptions() string {
	if m != nil {
		return m.Descriptions
	}
	return ""
}

func init() {
	proto.RegisterType((*Clients)(nil), "main.Clients")
}

func init() {
	proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c)
}

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x9a,
	0xcc, 0xc8, 0xc5, 0xee, 0x0c, 0x16, 0x2e, 0x16, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0d, 0x62, 0xf2, 0x74, 0x11, 0x92, 0xe1, 0xe2, 0x74, 0xcb, 0x2c, 0x2a, 0x2e,
	0xf1, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x08, 0x08, 0x49, 0x71,
	0x71, 0xf8, 0x24, 0x42, 0x25, 0x99, 0xc1, 0x92, 0x70, 0x3e, 0x48, 0x2e, 0x20, 0xb1, 0xb8, 0xb8,
	0x3c, 0xbf, 0x28, 0x45, 0x82, 0x05, 0x22, 0x07, 0xe3, 0x0b, 0x29, 0x71, 0xf1, 0xb8, 0xa4, 0x16,
	0x27, 0x17, 0x65, 0x16, 0x94, 0x64, 0xe6, 0xe7, 0x15, 0x4b, 0xb0, 0x82, 0xe5, 0x51, 0xc4, 0x92,
	0xd8, 0xc0, 0x4e, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x80, 0xe2, 0x61, 0xe5, 0xb2, 0x00,
	0x00, 0x00,
}
